### ISSUE TITLE
any examples for how to save the dual mesh to obj file?

### ISSUE THREAD

**Issue by GuangfuWang** [dengwirda/dual-mesh#1]
Hi, i would like to save the dual mesh of a given mesh to obj file but could know how to do that, can anybody help?

**Comment by dengwirda** [comment]
No I don't have direct support for this at present. The `*.obj` file format is [documented though](https://en.wikipedia.org/wiki/Wavefront_.obj_file), and it seems that exporting a Voronoi mesh as a collection of vertices (`v` tags) and polygons (`f` tags) should be possible.
I'll close this for now, but let me know if you have follow-up questions.

**Comment by GuangfuWang** [comment]
> No I don't have direct support for this at present. The `*.obj` file format is [documented though](https://en.wikipedia.org/wiki/Wavefront_.obj_file), and it seems that exporting a Voronoi mesh as a collection of vertices (`v` tags) and polygons (`f` tags) should be possible. I'll close this for now, but let me know if you have follow-up questions.

thanks for you kindly help! I have figure out using blender python API to converte a *.obj file to its dual mesh and save it to *.obj. anyway huge thanks!
